### ************************************
# API das músicas
#

###
# URL
@url=http://localhost:8000

### -------------------------------------
# Principal 

###
# (PING) Verificar aplicação web
GET {{url}}

###
# Post em '/' não existe.
POST {{url}}

{}

### -------------------------------------
# Músicas 

###
# URL base para a api de música
@apiMusica={{url}}/api/musicas

###
# Cadastra/salva uma nova música
POST {{apiMusica}}

{
    "nome": "Estoy Aquí",
    "artista": "Shakira",
    "tempo": 233
}


###
# Pesquisar música pelo código.
# Depois do '/' informe o código uuid desejado
GET {{apiMusica}}/informe-codigo

###
# Pesquisar todas as músicas.
GET {{apiMusica}}


###
# Atualizar todos os dados da música pelo código
# Ajuste o código uuid conforme o necessário
PUT {{apiMusica}}/codigo

{
    "nome": "outro nome",
    "artista": "outro artista",
    "tempo": 123    
}

###
# Remover a música pelo código
# Ajuste o código conforme o seu teste.
DELETE {{apiMusica}}/codigo-informado

###
# Etapa 1 até aqui
###

###
# Palavra para a pesquisa que contém
@palavraMusica=pes

###
# Pesquisar todas as músicas que contém a palavra informada
# no nome da música.
GET {{apiMusica}}/?nome={{palavraMusica}}

###
